---
title: "Linear_reg_covid"
author: "Yuting Li"
date: "4/19/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(car)
```

```{r}
data = read.csv("model_data_final.csv")
```

### Drop unnecessary columns
```{r}
data = data[-c(1,2,4,9,10,12,13)]
```

### Standardize data
```{r}
# data <- as.data.frame(scale(data))
```

##### First run a regression model with all variables for a quick check for multicollinearity
```{r}
model <- lm(infection_rate ~ ., data = data)
```

```{r}
summary(model)
```

### check multicolinearity
```{r}
car::vif(model)
```

Drop airport_density_sqkm

### Rerun model after fropping airport_density_sqkm
```{r}
model1 <- lm(infection_rate ~.-airport_density_sqkm, data = data)
```

```{r}
car::vif(model1)
```

All the VIF values are less than 10, so there's no evidence of strong multicollinearity in the model.

```{r}
summary(model1)
```

##### Run Stepwise Regression
```{r}
k <- olsrr::ols_step_forward_p(model1, details = TRUE)
```

```{r}
k$model
```

```{r}
model_final <- lm(infection_rate ~ GS+aging+pop_density_sqkm+education_index+avg_principle_cost+PC+surgical_quality, data = data)
```

```{r}
summary(model_final)
```


